spring.application.name=banking-app-backend
server.port=8080

spring.profiles.active=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:local-dev-only-jwt-secret-local-dev-only-jwt-secret-2026}
jwt.expiration=${JWT_EXPIRATION:5000}
