spring.datasource.url=jdbc:postgresql://postgres-db:5432/banking_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:7a6e7d2f16fcb64b1cb0e5d0a4f31dbb2d80f8b4e0f2db68c94b9}
jwt.expiration=${JWT_EXPIRATION:5000}